name: Static Site CI
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  static-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: upptime/uptime-monitor@v1.37.0
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./site/__sapper__/export
          cname: status.brettspielfreunde.net
